Перенёс сериализацию в метод экземпляра MessageParams
Вызов статического метода не сочетается с ограничем Where, приводит к ошибке
LinqToDB.Linq.LinqException: 'ToXDocument(...)' cannot be converted to SQL.